### ISSUE TITLE
populate the 2nd, 3rd and 4th graph in Grafana

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/istio-tutorial#34]
Only the 1st column is ever populated in Grafana

https://screencast.com/t/2NQ7YK3PtY

**Comment by rafabene** [comment]
One workaround is to add the request parameter "var-source=All" in the URL. Example: http://grafana-istio-system.192.168.64.16.nip.io/dashboard/db/istio-dashboard?var-source=All

Now I'm investigation why the $source variable in Grafana always comes null.

**Comment by rafabene** [comment]
Bookinfo shows that the incoming traffic comes from Ingress. Kube Ingress has an integration with Istio: https://istio.io/docs/tasks/traffic-management/ingress.html

Since we are using OpenShift, the Ingress doesn't come selected in Grafana. To have those metrics we need to select "All sources" in Grafana console.
<img width="370" alt="screenshot 2018-02-27 18 41 39" src="https://user-images.githubusercontent.com/30131/36761609-def1b73e-1bed-11e8-9f70-67ba3261ddbd.png">

**Comment by rafabene** [comment]
I've just update readme.md with a workaround for it.

**Comment by rafabene** [comment]
It seems that this issue is being handled in the upstream at https://github.com/istio/istio/issues/3099

**Comment by jeffmendoza** [comment]
Fix is here: https://github.com/istio/istio/pull/3524

**Comment by rafabene** [comment]
Solved in 0.6.0
